src/Entity/Caisse.php
<?php

namespace App\Entity;

use App\Repository\CaisseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CaisseRepository::class)]
class Caisse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $CreatAt = null;

    #[ORM\Column]
    private ?float $TotalFrais = null;

    #[ORM\Column]
    private ?float $totalVente = null;

    #[ORM\Column]
    private ?float $totalDettePayer = null;

    #[ORM\Column]
    private ?float $TotalDusPayer = null;

    #[ORM\Column]
    private ?float $TotalCommande = null;

    #[ORM\Column]
    private ?float $benefice = null;

    #[ORM\ManyToOne(inversedBy: 'caisse')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Point $point = null;

    public function __construct(){
        $date = new \DateTimeImmutable();
        $this->CreatAt = new \DateTimeImmutable($date->format('Y-m-d H:i'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatAt(): ?\DateTimeImmutable
    {
        return $this->CreatAt;
    }

    public function setCreatAt(\DateTimeImmutable $CreatAt): static
    {
        $this->CreatAt = $CreatAt;

        return $this;
    }

    public function getTotalFrais(): ?float
    {
        return $this->TotalFrais;
    }

    public function setTotalFrais(float $TotalFrais): static
    {
        $this->TotalFrais = $TotalFrais;

        return $this;
    }

    public function getTotalVente(): ?float
    {
        return $this->totalVente;
    }

    public function setTotalVente(float $totalVente): static
    {
        $this->totalVente = $totalVente;

        return $this;
    }

    public function getTotalDettePayer(): ?float
    {
        return $this->totalDettePayer;
    }

    public function setTotalDettePayer(float $totalDettePayer): static
    {
        $this->totalDettePayer = $totalDettePayer;

        return $this;
    }

    public function getTotalDusPayer(): ?float
    {
        return $this->TotalDusPayer;
    }

    public function setTotalDusPayer(float $TotalDusPayer): static
    {
        $this->TotalDusPayer = $TotalDusPayer;

        return $this;
    }

    public function getTotalCommande(): ?float
    {
        return $this->TotalCommande;
    }

    public function setTotalCommande(float $TotalCommande): static
    {
        $this->TotalCommande = $TotalCommande;

        return $this;
    }

    public function getBenefice(): ?float
    {
        return $this->benefice;
    }

    public function setBenefice(float $benefice): static
    {
        $this->benefice = $benefice;

        return $this;
    }

    public function getPoint(): ?Point
    {
        return $this->point;
    }

    public function setPoint(?Point $point): static
    {
        $this->point = $point;

        return $this;
    }
}

src/Entity/DetteParVente.php
<?php

namespace App\Entity;

use App\Repository\DetteParVenteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetteParVenteRepository::class)]
class DetteParVente extends DD
{

    #[ORM\Column]
    private ?float $benefice = null;

    #[ORM\OneToMany(mappedBy: 'detteParVente', targetEntity: DetailVc::class)]
    private Collection $detaillDette;

    #[ORM\ManyToOne(inversedBy: 'detteParVentes')]
    private ?User $user = null;

    #[ORM\Column]
    private ?bool $benefComplet = false;

    public function __construct()
    {
        parent::__construct();
        $this->detaillDette = new ArrayCollection();
        $this->setTypeDD("detteParVente");
    }


    public function getBenefice(): ?float
    {
        return $this->benefice;
    }

    public function setBenefice(float $benefice): static
    {
        $this->benefice = $benefice;

        return $this;
    }

    /**
     * @return Collection<int, DetailVc>
     */
    public function getDetaillDette(): Collection
    {
        return $this->detaillDette;
    }

    public function addDetaillDette(DetailVc $detaillDette): static
    {
        if (!$this->detaillDette->contains($detaillDette)) {
            $this->detaillDette->add($detaillDette);
            $detaillDette->setDetteParVente($this);
        }

        return $this;
    }

    public function removeDetaillDette(DetailVc $detaillDette): static
    {
        if ($this->detaillDette->removeElement($detaillDette)) {
            // set the owning side to null (unless already changed)
            if ($detaillDette->getDetteParVente() === $this) {
                $detaillDette->setDetteParVente(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function isBenefComplet(): ?bool
    {
        return $this->benefComplet;
    }

    public function setBenefComplet(bool $benefComplet): static
    {
        $this->benefComplet = $benefComplet;

        return $this;
    }

}

src/Controller/DetteParVenteController.php
<?php

namespace App\Controller;

use App\Entity\Vente;
use App\Entity\DetailVC;
use App\Entity\Payement;
use App\Entity\DetteParVente;
use App\Repository\UserRepository;
use App\Form\DetteParVenteFormType;
use App\Repository\PointRepository;
use App\Repository\VenteRepository;
use App\Repository\ProduitRepository;
use App\Repository\PayementRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\DetteParVenteRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DetteParVenteController extends AbstractController
{
    #[Route('/dette/par/vente', name: 'app_dette_par_vente')]
    public function index(DetteParVenteRepository $detteParVenteRepository,PaginatorInterface $paginator,Request $request,Session $session): Response
    {
        if($session->has("idPay") ){
            $session->remove("idPay"); 
        }
        $filtre = [];
        $filtre['pointId'] = $session->get('pointActive')->getId();
        if($session->has("dateFiltreDue")){
            $filtre['dateFiltreDue'] = $date = $session->get("dateFiltreDue");
        }
        
        if($session->has("dateFiltreClient")){
            $filtre['dateFiltreClient'] = $session->get("dateFiltreClient");
            $client = $session->get("dateFiltreClient");
        }

        $detteparVente = $detteParVenteRepository->findByFiltre($filtre);
        
        $pagination = $paginator->paginate(
            $detteparVente, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        $total =  $detteParVenteRepository->totalFiltre($filtre);
        return $this->render('dette_par_vente/index.html.twig', [
            "pagination" => $pagination,
            "total" => $total,
            "date" => $date??"",
            "client" => $client??""
        ]);
    }

    #[Route('/detteParVente/filtre', name: 'app_detteParVente_filtre')]
    public function filtre(Request $request,Session $session): Response
    {
        if($request->isXmlHttpRequest() || $request->query->get('attrclient') != null){
            $session->set("dateFiltreClient" , $request->query->get('attrclient'));
        }

        if($request->query->get('attrclient') === ""){
            $session->remove("dateFiltreClient");
        }

        if($request->isXmlHttpRequest() || $request->query->get('attrdate-due') != null){            
            $session->set("dateFiltreDue" , $request->query->get('attrdate-due'));
        }

        if($request->query->get('attrdate-due') === ""){
            $session->remove("dateFiltreDue");
        }
        return new JsonResponse($this->generateUrl("app_dette_par_vente"));
    }

    // AJOUTER DETTE PAR VENTE ON 
        #[Route('/detteParVente/DoVente', name: 'app_vendre_dodetteParVente')]
        public function dodetteParVente(PointRepository $pointRepository,UserRepository $userRepository,ProduitRepository $produitRepository,EntityManagerInterface $manager,Request $request,Session $session): Response
        {
                $produitpaniers = $session->get("produits");
                $session->remove("produits");
                $detteParVente = new DetteParVente();
                $detteParVente->setPoint($pointRepository->find($session->get('pointActive')->getId()));
                $vente = new Vente();
                $vente->setPoint($pointRepository->find($session->get('pointActive')->getId()));
                $total = 0;
                $benefice = 0;       
                foreach ($produitpaniers as $pn){
                    $total += $pn->getPrixVenteFix() * $pn->getQte();
                    $benefice += ($pn->getPrixVenteFix() * $pn->getQte()) - ($pn->getPrixAchat() * $pn->getQte());
                    $prod = $produitRepository->find($pn->getId());            
                    // dd($prod->getQte()-$pn->getQte());
                    $produitRepository->updateQte($prod->getQte()-$pn->getQte(),$pn->getId());
                    $detailVc = new DetailVC();
                    $detailVc->setQteVente($pn->getQte());
                    $detailVc->setPrixVente($pn->getPrixVenteFix());
                    $detailVc->setProduit($prod);
                    $detailVc->setVC($vente);
                    $detailVc->setDetteParVente($detteParVente);
                    $detailVc->setPrixAchat($prod->getPrixAchat());
                    $manager->persist($detailVc);
                }     
                $user = $userRepository->findOneBy(["email"=>$this->getUser()->getUserIdentifier()]);
                $detteParVente->setUser($user);
                $detteParVente->setBenefice($benefice);
                $detteParVente->setLibelle("dette ajouter par ".$user->getNomComplet());
                $detteParVente->setMontantTotal($total);
                $detteParVente->setMontantRestant($total);
                $detteParVente->setMontantDonnee(0);
                $detteParVente->setClient($session->get("client"));
                $vente->setClient($session->get("client"));
                $vente->setTotal(0);
                $vente->setUser($user);
                $manager->persist($vente);        
                $manager->persist($detteParVente);        
                $manager->flush();
                $succes["venteSucces"] = "dette Par Vente ajouter";
                $session->set("succes",$succes);
                return  $this->redirectToRoute('app_vendre');;
        }
    // AJOUTER DETTE PAR VENTE OFF
    
    // PAYEMENT DETTE PAR VENTE ON 
        #[Route('/detteParVente/pay/{id?}', name: 'app_detteParVente_pay')]
        public function payer($id,VenteRepository $venteRepository,DetteParVenteRepository $dette,Request $request,EntityManagerInterface $manager,Session $session): Response
        {
            if($id == null){
                $detteparVente = new DetteParVente();
            }else{
                $detteparVente = $dette->find($id);
                $session->set("montantDonnee",$detteparVente->getMontantDonnee());
            }
            $form = $this->createForm(DetteParVenteFormType::class, $detteparVente);
            $form->handleRequest($request);
            // dd($detteparVente);
            if ($form->isSubmitted() && $form->isValid()) {
                // dd($detteparVente);
                if ($detteparVente->getMontantDonnee() > $detteparVente->getMontantRestant()) {
                    $error['erreurMontant'] = "le montant donner est supperieur au reste a payer";
                }else{
                    $payement = new Payement();
                    $payement->setMontantVerser($detteparVente->getMontantDonnee());  
                    $detteparVente->setMontantRestant($detteparVente->getMontantRestant() - $payement->getMontantVerser());

                    if($session->has("montantDonnee")){
                        $detteparVente->setMontantDonnee($detteparVente->getMontantDonnee() + $session->get("montantDonnee"));                   
                        $session->remove("montantDonnee");
                    }

                    if($detteparVente->getMontantRestant() == 0) {
                        $vente = $venteRepository->find($detteparVente->getDetaillDette()[0]->getVC()->getId());
                        $vente->setTotal($detteparVente->getMontantTotal());
                        $manager->persist($vente);
                    } 

                    
                    $payement->setDetteParVente($detteparVente);
                    $payement->setNumero("payementN°".$payement->getId().$payement->getCreatAt()->format('d-m-Y').$payement->getCreatAt()->format('H:i'));
                    $payement->setDD($detteparVente);
                    $manager->persist($detteparVente);                    
                    $manager->persist($payement);
                    $manager->flush();
                    $succes["paySucces"] = "payement réussi";
                }
            }
            return $this->render('dette_par_vente/formPay.html.twig', [
                "form" => $form->createView(),
                "due" => $detteparVente,
                "error" => $error??[],
                "succes" => $succes??[]
            ]);
        }
    // PAYEMENT DETTE PAR VENTE OFF
}

templates/dette_par_vente/formPay.html.twig
{% extends 'base.html.twig' %} {% block title %}Dette Pay{% endblock %} {% block
content %}
<div class="mb-3 text-2xl">payement de Dette</div>
<div class="mb-3 text-2xl text-red-600">{{error['erreurMontant']??""}}</div>

<p class="text-base text-red-500">{{succes['paySucces']??""}}</p>

{{ form_start(form) }}
<div class="">
  <div class="p-2 text-2xl ">client : <span class="text-yellow-600 text-bold">{{due.client}}</span></div>
  <div class="p-2 text-2xl ">libelle : <span class="text-yellow-600 text-bold">{{due.libelle}}</span></div>
  <div class="p-2 text-2xl ">date : <span class="text-yellow-600 text-bold">{{due.creatAt.format("Y-m-d")}}</span></div>
  <div class="p-2 text-2xl ">montant total : <span class="text-yellow-600 text-bold">{{due.montantTotal}}fr</span></div>
  <div class="p-2 text-2xl ">montant restant : <span class="text-yellow-600 text-bold">{{due.montantRestant}}fr</span></div>
  <div class="p-2 text-2xl ">montant donnee : <span class="text-yellow-600 text-bold">{{due.montantDonnee}}fr</span></div>
</div>
{{ form_widget(form) }}
<input
  type="submit"
  class="float-right px-4 py-2 bg-gray-500 cursor-pointer rounded-xl"
  value="payer"
/>
{{ form_end(form) }}

<h1 class="my-10 text-5xl text-center text-yellow-900 ">les produit du dette</h1>
{# TABLE PRODUIT ON  #}
    <div class="m-4 overflow-x-auto bg-white dark:bg-neutral-700">

        <!-- Table -->
        <table class="min-w-full text-base text-left whitespace-nowrap">

            <!-- Table head -->
            <thead class="tracking-wider uppercase border-b-2 dark:border-neutral-600 bg-neutral-50 dark:bg-neutral-800">
                <tr>
                    <th scope="col" class="px-6 py-5">
                    nbr
                    </th>            
                    <th scope="col" class="px-6 py-5">
                    categorie
                    </th>            
                    <th scope="col" class="px-6 py-5">
                    detail
                    </th>
                    <th scope="col" class="px-6 py-5">
                    qte
                    </th>
                    <th scope="col" class="px-6 py-5">
                    prix
                    </th>
                    <th scope="col" class="px-6 py-5">
                    total
                    </th>
                </tr>
            </thead>

            <!-- Table body -->
                <tbody>
                    {% for i,item in due.detaillDette %}
                        <tr class="border-b dark:border-neutral-600">                        
                            <td class="px-6 py-5">{{i+1}}</td>
                            <td class="px-6 py-5">{{item.produit.categorie}}</td>
                            <td class="px-6 py-5">{{item.produit.detail}}</td>
                            <td class="px-6 py-5">{{item.qteVente}}</td>                            
                            <td class="px-6 py-5">{{item.prixVente}}</td>  
                            <td class="px-6 py-5">{{item.prixVente * item.qteVente}}</td>                              
                        </tr>                
                    {% endfor %}
                </tbody>                    
                <tfoot>
                    <tr class="border-b dark:border-neutral-600">
                        <th  class="px-6 py-5 text-2xl">total :</th>
                        <th colspan="5" class="px-6 py-5 text-2xl"><span class="text-yellow-900 ">{{due.montantTotal}}fr</span></th>
                    </tr>
                </tfoot>
        </table>

    </div>
{# TABLE PRODUIT OFF  #}
{% endblock content %}

templates/dette_par_vente/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dette{% endblock %}

{% block content %}
{# FORM FILTRE ON #}
    <div class="w-full p-4 bg-gray-200">
        <div class="flex items-center w-full gap-3">
             <div class="w-1/3">
                <input data-path="{{path('app_detteParVente_filtre')}}" placeholder="yyyy-mm-dd" class="w-full" type="text" value="{{date??""}}" name="" id="date-due">
            </div>

            <div class="w-1/3">
                <input data-path="{{path('app_detteParVente_filtre')}}" placeholder="entrer le client" class="w-full" type="text" value="{{client??""}}" name="" id="client">
            </div>	
		
        </div>
    </div>
{# FORM FILTRE OFF #}

{# TABLE ON  #}
    <div class="m-4 overflow-x-auto bg-white dark:bg-neutral-700">

        <!-- Table -->
        <table class="min-w-full text-xs text-left whitespace-nowrap">

            <!-- Table head -->
            <thead class="tracking-wider uppercase border-b-2 dark:border-neutral-600 bg-neutral-50 dark:bg-neutral-800">
                <tr>
                    <th scope="col" class="px-6 py-5">
                    date
                    </th>            
                    <th scope="col" class="px-6 py-5">
                    client
                    </th>
                    <th scope="col" class="px-6 py-5">
                    libelle
                    </th>
                    <th scope="col" class="px-6 py-5">
                    montant total
                    </th>
                    <th scope="col" class="px-6 py-5">
                    montant restant
                    </th>
                    <th scope="col" class="px-6 py-5">
                    action            
                    </th>
                </tr>
            </thead>

            <!-- Table body -->
            <tbody>
                {% for item in pagination %}
                    <tr class=" {{item.montantRestant == 0 ? 'bg-green-200' : ''}} border-b dark:border-neutral-600">
                        <th scope="row" class="px-6 py-5">{{item.creatAt.format("d-m-Y")}}</th>
                        <td class="px-6 py-5">{{item.client}}</td>
                        <td class="px-6 py-5">{{item.libelle}}</td>
                        <td class="px-6 py-5">{{item.montantTotal}}fr</td>
                        <td class="px-6 py-5">{{item.montantRestant}}fr</td>
                        <td class="px-6 py-5">
                            <a target="_blank" href="{{path('app_detteParVente_pay',{id:item.id})}}" class="p-2 bg-yellow-400 rounded">payer</a>
                            <a href="{{path('app_payment_list',{id:item.id})}}" class="p-2 bg-yellow-700 rounded">payement</a>
                        </td>
                    </tr>                
                {% endfor %}
            </tbody>

            <!-- Table footer -->
            <tfoot class="border-t-2 dark:border-neutral-600">
            <tr>
                <th class="px-6 py-5">Total:</th>
                <td class="px-6 py-5">{{total??0}}fr</td>
                <td class="px-6 py-5"></td>
                <td class="px-6 py-5"></td>
                <td class="px-6 py-5"></td>
                <td class="px-6 py-5"></td>
            </tr>
            </tfoot>

        </table>

    </div>
{# TABLE OFF  #}

{# KPN PAGINATION ON  #}
	<div class="py-2 text-center">		
			{{ knp_pagination_render(pagination) }}		
	</div>
{# KPN PAGINATION OFF #}

{% endblock %}